# Enforces conventional commits on pull requests
# Ref: https://github.com/marketplace/actions/conventional-pull-request
name: Conventional pull request
run-name: Conventional commits pull request

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  lint-pr:
    if: "${{ !contains(github.event.pull_request.title, 'chore(main): release') }}"
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate
        uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: "./commitlint.config.js"
